[package]
name = "rquickjs-macro"
version = "0.4.0-beta.0"
authors = ["K. <kayo@illumium.org>", "Mees Delzenne <mees.delzenne@gmail.com>"]
edition = "2021"
license = "MIT"
readme = "README.md"
description = "Procedural macros for rquickjs"
keywords = ["quickjs", "ecmascript", "javascript", "es6", "es2020"]
categories = ["api-bindings"]
repository = "https://github.com/DelSkayn/rquickjs.git"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
proc-macro-crate = "1"
proc-macro-error = "1"
quote = "1"
ident_case = "1"
fnv = "1"
indexmap = "1"

[dependencies.darling]
version = "0.20"

[dependencies.syn]
version = "2"
features = ["full"]

[dependencies.phf_shared]
version = "0.10"
optional = true

[dependencies.phf_generator]
version = "0.10"
optional = true

[dependencies.rquickjs-core]
path = "../core"
version = "0.4.0-beta.0"
features = ["loader"]

[dev-dependencies.difference]
version = "2"

[dev-dependencies.rquickjs]
path = ".."
version = "0.4.0-beta.0"
features = ["macro", "classes", "properties", "futures"]

[dev-dependencies.async-std]
version = "1"
features = ["attributes"]

[features]
phf = ["phf_shared", "phf_generator"]
