[package]
name = "import-attributes"
version = "0.11.0"
authors = ["K. <kayo@illumium.org>"]
edition = "2021"
publish = false

[dependencies.rquickjs]
path = "../.."
default-features = false
features = ["rust-alloc", "loader"]
